### ISSUE TITLE
Change Required following update of Development Build?

### ISSUE THREAD

**Issue by TarnShaord** [zesterer/openmw-shaders#39]
Hi Zesterer

Great mod which I have used on an older openMW development build. I have just trued reinstalling on build 76cba95a44 (from 3 days ago) and then tried installing the openmw-shaders and it was not recognising. Some basic investigation has indicated that the file structure under resources/shaders directory has changed. where as before all the files were under the shaders directory there is now 3 directories 'compatibility', 'core' and 'lib' with all files now in those directories.

Can you please confirm that this is the issues and what is required to updated this mod.

Thanks

**Comment by Para0x** [comment]
Can confirm the folder structure has changed, as well as the file naming as well. 

An example would be 

> shadowcasting_fragment.glsl
> shadowcasting_vertex.glsl
becomes
> shadowcasting.frag
> shadowcasting.vert

Since I don't really understand shaders, I'm not sure if you can just rename your files and distribute them where needed or if the entire shader mod needs a complete rework due to the update.

**Comment by zesterer** [comment]
I believe the shaders need updating according to upstream changes. I don't currently have time to do this, but if anybody is interested it would be a case of going through the upstream changes that have occurred recently and applying these shaders on top of them.
